/**
 * ⚠️ DEPRECATED: Este arquivo está sendo substituído por @/lib/supabaseClient
 * 
 * Por favor, use:
 * import { supabase, isSupabaseConfigured } from '@/lib/supabaseClient';
 * 
 * Este arquivo re-exporta do supabaseClient para compatibilidade com código gerado.
 */

// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

// Re-exportar do cliente único
import { supabase as baseSupabase, isSupabaseConfigured } from '@/lib/supabaseClient';

// Type assertion para manter compatibilidade com Database type
export const supabase = baseSupabase as ReturnType<typeof import('@supabase/supabase-js').createClient<Database>>;
export { isSupabaseConfigured };