// ⚠️ ATENÇÃO: Este arquivo não está sendo usado atualmente
// Todos os arquivos usam @/lib/supabase para garantir URL única global
// Este arquivo é mantido apenas para compatibilidade

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ⚠️ CRÍTICO: Usar a mesma URL global para garantir que todos os dispositivos usam o mesmo backend
const SUPABASE_URL_GLOBAL = 'https://kfyzcqaerlwqcmlbcgts.supabase.co';
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || SUPABASE_URL_GLOBAL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// ⚠️ RECOMENDADO: Use @/lib/supabase em vez deste arquivo

export const supabase = createClient<Database>(
  SUPABASE_URL === SUPABASE_URL_GLOBAL || !SUPABASE_URL.includes('localhost') 
    ? SUPABASE_URL 
    : SUPABASE_URL_GLOBAL, 
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key', 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);